# Generated by Django 5.1.4 on 2026-08-07 10:30

import apps.accounts.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('phone_number', models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be stored as +91XXXXXXXXXX.', regex='^\\+91[6-9]\\d{9}$')])),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('viewer', 'Viewer')], db_index=True, default='staff', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['is_active', 'is_deleted'], name='accounts_us_is_acti_d91a15_idx')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at',),
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_de_user_id_3a43c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_device')],
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('phone_number', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be stored as +91XXXXXXXXXX.', regex='^\\+91[6-9]\\d{9}$')])),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_reference', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='accounts_ot_phone_n_20bb06_idx'), models.Index(fields=['expires_at', 'consumed_at'], name='accounts_ot_expires_1bcddf_idx')],
            },
        ),
    ]
