# Generated by Django 5.1.4 on 2026-08-07 10:30

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # gin_trgm_ops does not exist until CREATE EXTENSION pg_trgm has run,
        # so the extension migration must be applied first.
        ('files', '0001_enable_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(db_index=True, default='/', editable=False, max_length=2048)),
                ('depth', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded top-level categories that cannot be renamed or deleted.')),
                ('is_pinned', models.BooleanField(default=False)),
                ('file_count', models.PositiveIntegerField(default=0, editable=False)),
                ('subfolder_count', models.PositiveIntegerField(default=0, editable=False)),
                ('total_size_bytes', models.BigIntegerField(default=0, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folders.folder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FolderFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='folders.folder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent', 'is_deleted', 'position'], name='folders_fol_parent__a76225_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['path'], name='folder_path_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_deleted', '-updated_at'], name='folders_fol_is_dele_b17f47_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['depth', 'is_deleted'], name='folders_fol_depth_06f7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='folder_name_trigram_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), condition=models.Q(('is_deleted', False)), name='uniq_folder_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_deleted', False), ('parent__isnull', True)), name='uniq_root_folder_name'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 0)), name='folder_depth_non_negative'),
        ),
        migrations.AddIndex(
            model_name='folderfavorite',
            index=models.Index(fields=['user', '-created_at'], name='folders_fol_user_id_1bb7b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='folderfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'folder'), name='uniq_user_folder_favorite'),
        ),
    ]
