# Generated by Django 5.1.4 on 2026-08-07 10:30

import apps.files.models
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_enable_extensions'),
        ('folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('extension', models.CharField(db_index=True, max_length=20)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('archive', 'Archive'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('storage_provider', models.CharField(default='cloudinary', max_length=20)),
                ('public_id', models.CharField(db_index=True, max_length=512)),
                ('resource_type', models.CharField(default='raw', max_length=20)),
                ('secure_url', models.URLField(blank=True, default='', max_length=1024)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1024)),
                ('checksum', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Lowercase, de-duplicated free-text labels.', size=None)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.folder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='files.fileasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('public_id', models.CharField(max_length=512)),
                ('resource_type', models.CharField(default='raw', max_length=20)),
                ('secure_url', models.URLField(blank=True, default='', max_length=1024)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.fileasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='RecentFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_entries', to='files.fileasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-accessed_at',),
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(db_index=True, default=apps.files.models._generate_share_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, help_text='Null means unlimited until expiry.', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_note', models.CharField(blank=True, default='', max_length=255)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.fileasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['folder', 'is_deleted', '-created_at'], name='files_filea_folder__4e37c6_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['category', 'is_deleted'], name='files_filea_categor_dbc784_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['extension', 'is_deleted'], name='files_filea_extensi_dc5135_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['created_by', '-created_at'], name='files_filea_created_ba446b_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['is_deleted', '-deleted_at'], name='files_filea_is_dele_d1153c_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['-download_count'], name='files_filea_downloa_3e1733_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='file_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='file_tags_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='file_name_trigram_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('folder'), condition=models.Q(('is_deleted', False)), name='uniq_file_name_per_folder'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='file_size_non_negative'),
        ),
        migrations.AddIndex(
            model_name='filefavorite',
            index=models.Index(fields=['user', '-created_at'], name='files_filef_user_id_50a291_idx'),
        ),
        migrations.AddConstraint(
            model_name='filefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'file'), name='uniq_user_file_favorite'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['file', '-version_number'], name='files_filev_file_id_6ae327_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(fields=('file', 'version_number'), name='uniq_file_version_number'),
        ),
        migrations.AddIndex(
            model_name='recentfile',
            index=models.Index(fields=['user', '-accessed_at'], name='files_recen_user_id_2c43fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='recentfile',
            constraint=models.UniqueConstraint(fields=('user', 'file'), name='uniq_user_recent_file'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token'], name='files_share_token_cf5ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['expires_at', 'revoked_at'], name='files_share_expires_1269e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['created_by', '-created_at'], name='files_share_created_1380ca_idx'),
        ),
    ]
